# Generated by Django 5.0.4 on 2024-05-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcenter', '0002_bannermain_name_sidebanner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='company',
            new_name='category',
        ),
    ]
