# Generated by Django 5.0.4 on 2024-05-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcenter', '0003_rename_company_articles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='button',
        ),
    ]
