# Generated by Django 5.0.4 on 2024-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcenter', '0004_remove_articles_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='typear',
            field=models.CharField(choices=[('mainar', 'Main Article'), ('fourar', 'Four Articles'), ('marque', 'Marquee Articles'), ('multimedia', 'Multimedia Articles')], default='simple', max_length=100),
        ),
    ]
