# Generated by Django 5.0.4 on 2024-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcenter', '0005_articles_typear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='typear',
            field=models.CharField(choices=[('simple', 'Simple Articles'), ('mainar', 'Main Article'), ('fourar', 'Four Articles'), ('marque', 'Marquee Articles'), ('multimedia', 'Multimedia Articles'), ('univer', 'Univer Articles'), ('vacational', 'Vacational Articles'), ('news', 'News'), ('official', 'Oficiall News')], default='simple', max_length=100),
        ),
    ]
