# Generated by Django 5.0.4 on 2024-07-17 17:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcenter', '0008_laws_alter_articles_typear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('description_tm', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('docs', models.FileField(upload_to='docs/')),
                ('views', models.IntegerField(default=0)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='typear',
            field=models.CharField(choices=[('simple', 'Simple Articles'), ('mainar', 'Main Article'), ('fourar', 'Four Articles'), ('marque', 'Marquee Articles'), ('multimedia', 'Multimedia Articles'), ('univer', 'Univer Articles'), ('vacational', 'Vacational Articles'), ('news', 'News'), ('official', 'Oficiall News'), ('uni_news', 'Univer News'), ('vac_news', 'Vacational News'), ('news_laws', 'Laws News')], default='simple', max_length=100),
        ),
    ]
