# Generated by Django 5.0.4 on 2024-07-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcenter', '0009_docs_alter_articles_typear'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_marquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='typear',
            field=models.CharField(choices=[('simple', 'Simple Articles'), ('mainar', 'Main Article'), ('fourar', 'Four Articles'), ('marque', 'Marquee Articles'), ('multimedia', 'Multimedia Articles'), ('univer', 'Univer Articles'), ('vacational', 'Vacational Articles'), ('lycee', 'Lycee Articles'), ('news', 'News'), ('official', 'Oficiall News'), ('uni_news', 'Univer News'), ('vac_news', 'Vacational News'), ('lyc_news', 'Lycee News'), ('news_laws', 'Laws News')], default='simple', max_length=100),
        ),
    ]
