# Generated by Django 5.0.4 on 2024-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcenter', '0010_articles_is_marquee_alter_articles_typear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('vacancy_url', models.CharField(max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='typear',
            field=models.CharField(choices=[('simple', 'Simple Articles'), ('mainar', 'Main Article'), ('fourar', 'Four Articles'), ('multimedia', 'Multimedia Articles'), ('univer', 'Univer Articles'), ('vacational', 'Vacational Articles'), ('lycee', 'Lycee Articles'), ('news', 'News'), ('official', 'Oficiall News'), ('uni_news', 'Univer News'), ('vac_news', 'Vacational News'), ('lyc_news', 'Lycee News'), ('news_laws', 'Laws News')], default='simple', max_length=100),
        ),
    ]
